server:
  port: 5000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.8:5432/grade-curricular
    password: Postgres2021!
    username: postgres
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    date-format: yyyy-MM-dd
    deserialization:
      fail-on-unknown-properties: true